import {
  CapperSymbol,
  ColumnSymbol,
  CompressorSymbol,
  ConveyorSymbol,
  AcMainsSymbol,
  AcMotorLoadSymbol,
  ChargerSymbol,
  DcSourceSymbol,
  FillerSymbol,
  FlowSensorSymbol,
  GenericMachineSymbol,
  HeatExchangerSymbol,
  FuseBlockSymbol,
  HmiPanelSymbol,
  IoCardSymbol,
  LithiumBatterySymbol,
  MfmMeterSymbol,
  McbBreakerSymbol,
  MixerSymbol,
  MotorSymbol,
  PanelBackplateSymbol,
  PackagingSymbol,
  PressureSensorSymbol,
  PlcRackSymbol,
  PumpSymbol,
  Rs485BusSymbol,
  SkidSymbol,
  SolarInverterSymbol,
  TankSymbol,
  ValveSymbol,
  VfdDriveSymbol,
} from './EquipmentSymbols'
import { OpenIndustryAssetSymbol } from './OpenIndustryAssetSymbol'

export const equipmentRegistry = {
  tank: TankSymbol,
  panelBackplate: PanelBackplateSymbol,
  dcSource: DcSourceSymbol,
  acMains: AcMainsSymbol,
  fuseBlock: FuseBlockSymbol,
  mcbBreaker: McbBreakerSymbol,
  charger: ChargerSymbol,
  lithiumBattery: LithiumBatterySymbol,
  solarInverter: SolarInverterSymbol,
  vfdDrive: VfdDriveSymbol,
  acMotorLoad: AcMotorLoadSymbol,
  mfmMeter: MfmMeterSymbol,
  plcRack: PlcRackSymbol,
  hmiPanel: HmiPanelSymbol,
  rs485Bus: Rs485BusSymbol,
  ioCard: IoCardSymbol,
  pump: PumpSymbol,
  motor: MotorSymbol,
  flowSensor: FlowSensorSymbol,
  pressureSensor: PressureSensorSymbol,
  valve: ValveSymbol,
  conveyor: ConveyorSymbol,
  mixer: MixerSymbol,
  heatExchanger: HeatExchangerSymbol,
  compressor: CompressorSymbol,
  column: ColumnSymbol,
  skid: SkidSymbol,
  filler: FillerSymbol,
  capper: CapperSymbol,
  packaging: PackagingSymbol,
  packagingLabeling: PackagingSymbol,
  openIndustryAsset: OpenIndustryAssetSymbol,
  genericMachine: GenericMachineSymbol,
}
