import {
  CapperSymbol,
  ColumnSymbol,
  CompressorSymbol,
  ConveyorSymbol,
  FillerSymbol,
  FlowSensorSymbol,
  GenericMachineSymbol,
  HeatExchangerSymbol,
  MixerSymbol,
  MotorSymbol,
  PackagingSymbol,
  PressureSensorSymbol,
  PumpSymbol,
  SkidSymbol,
  TankSymbol,
  ValveSymbol,
} from './EquipmentSymbols'
import { OpenIndustryAssetSymbol } from './OpenIndustryAssetSymbol'

export const equipmentRegistry = {
  tank: TankSymbol,
  pump: PumpSymbol,
  motor: MotorSymbol,
  flowSensor: FlowSensorSymbol,
  pressureSensor: PressureSensorSymbol,
  valve: ValveSymbol,
  conveyor: ConveyorSymbol,
  mixer: MixerSymbol,
  heatExchanger: HeatExchangerSymbol,
  compressor: CompressorSymbol,
  column: ColumnSymbol,
  skid: SkidSymbol,
  filler: FillerSymbol,
  capper: CapperSymbol,
  packaging: PackagingSymbol,
  packagingLabeling: PackagingSymbol,
  openIndustryAsset: OpenIndustryAssetSymbol,
  genericMachine: GenericMachineSymbol,
}
